version: '3.7'

services:

  mariadb:
    image: arm64v8/mariadb
    container_name: mariadb
    volumes:
      - '.docker/data/db:/var/lib/mysql'
    ports:
      - 127.0.0.1:3307:3306
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - symfony

  nginx:
    image: nginx:1.17.9-alpine
    container_name: nginx
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
    networks:
      - symfony

  php:
    container_name: phpbin
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    networks:
      - symfony

networks:
  symfony: